CREATE DATABASE 03_CRUD_AUTHENTICATION_MYSQL;

USE 03_CRUD_AUTHENTICATION_MYSQL;

CREATE TABLE  employees (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    INDEX (name)
);

SELECT * FROM employees;